enum Agree {
  AGREE_USING_PERSONNEL_INFO = "AGREE_USING_PERSONNEL_INFO",
  AGREE_USING_SITE = "AGREE_USING_SITE",
  AGREE_HANDLING_PERSONNEL_INFO = "AGREE_HANDLING_PERSONNEL_INFO",
}

export default Agree;
